server:
  port: 80
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
webapp:
  title: XX有限公司报表平台
management:
   endpoint:
     beans:
       enabled: true
     web:
       exposure:
         include:*
     shutdown:
       enabled: true
mqtt:
  username: eam
  password: Eam#2020
  host: tcp://132.232.111.110:1883
  clientinid: eamServer
  topic: /init
  timeout: 10000
  keepalibe: 20

       
       
       
       